version: "3.8"

services:

  #PHP service
  php:
    build:
      context: .
    #   tagret: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8080"
    depends_on:
      - database

  #Database server
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DATABASE=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data: ~
